name: Run Only
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        run: python main.py
